### ISSUE TITLE
Nonmanual topic label dop

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#107]
Across files, events in the "topic/focus" field have dropped labels. The event bar still exists, but there is no longer a label. Screenshots in this report are from Rachel 43, but I have found the same issue in every file I have checked. 

(two labels missing)
![screen shot 2016-11-02 at 12 33 16 pm](https://cloud.githubusercontent.com/assets/15836242/19937680/9aceb9ce-a0f8-11e6-8e5d-78961af1831a.png)

(no labels missing-- it's not all labels, just some. I am not sure which are missing and which remain)
![screen shot 2016-11-02 at 12 34 37 pm](https://cloud.githubusercontent.com/assets/15836242/19937737/cd87ff92-a0f8-11e6-8bc2-9302a6caadc7.png)

**Comment by gregorydimitriadis** [comment]
What this appears to be is the result of a deleted label for the 'topic/focus' field. Judging by the coding schema (/newXMLfiles/defCodingScheme.xml) for all the fields in Signstream, these are the valid global labels for 'topic/focus':

FIELD ID="20" NAME="topic/focus" LABEL="topic/focus" COLOR="b3e00" TYPE="NMN" GROUP="GRAMMATICAL">
VALUE ID="2" NAME="focus/top1" LABEL="foc/top1" />
VALUE ID="3" NAME="top2" LABEL="top2" />
VALUE ID="4" NAME="top3" LABEL="top3"/>
VALUE ID="5" NAME="foc/prop-with-ref-to" LABEL="foc/ref" />
VALUE ID="6" NAME="sentence-initial adverb" LABEL="foc/adv" />
VALUE ID="7" NAME="focus" LABEL="focus" />
/FIELD

They have possible ID's from 2 to 7. What I see in the collection file for Rachel 43 (as probably is the case with the other collections Chelsea checked) is that for all of the blank event bars in the 'topic/focus' line, they are all marked with and ID of 8. I take that to mean that at some point in the past, there was another global label specified for 'topic/focus' in addition to the six above, and it had ID 8. Somewhere along the line, that label must have been removed from the coding schema. I'm not sure when that took place, since the earliest version of the coding schema file which I have only comes as shown above.

So, once value with ID 8 was deleted, all collections with that label in 'topic/focus' were unable to locate the proper value and label, and thus became blank. I can see this being resolved in a few ways:

1) If I knew what that value with ID of 8 was originally, I could add that back into the global coding schema file and push it out with the next release. Then, each affected collection file would need to be re-opened, (during the normal course of working with them is okay) verified that all previously blank 'topic/focus' values are now displaying the proper label, and then saved as such. That would solve the issue for all collection files, or at least one at a time. (I recommend this approach - but I first need to know what that value with ID of 8 was.)

2) All affected collection files (with blank values for 'topic/focus') can be parsed with a script and manually edited. I could either force everything marked with an ID of 8 to a value of another ID (from 2 to 7) or to another user-created value entirely. In this way, there would be no value of ID 8 going forward.

3) Leave everything as is and students can manually open each affected collection file and edit the blank labels for 'topic/focus' to something more appropriate and save as such. In this way also, there would be no value of ID 8 going forward.

So I will leave this as a question for @cneidle - as to which approach is preferred. I see that this issue may have implications/relations to #91 (the script you mentioned a few months back to replace some values for the 'topic/focus' field). Perhaps these two can be solved simultaneously, assuming we go with the first approach above and there is a mechanism to fix both by editing the global coding schema file.

**Comment by hammondcl** [comment]
I think this can be closed. I'm manually inputting labels for the blank ones so that I can be sure they're accurate.
