### ISSUE TITLE
Offsets extend past end of utterance

### ISSUE THREAD

**Issue by hammondcl** [DCS-LCSR/SignStream3#119]
The program is not supposed to allow you to extend events or offsets past the end of the utterance, but these in Rachel 53, U1 are outside of the boundaries. I have not encountered this in any other file so far and it appears to be only this utterance of this file. 
![screen shot 2017-02-13 at 12 29 16 pm](https://cloud.githubusercontent.com/assets/15836242/22894818/5cad5434-f1e8-11e6-8615-2cdcee54b717.png)

If I try to extend one past the end of the utterance, this warning appears: 
![screen shot 2017-02-13 at 12 30 48 pm](https://cloud.githubusercontent.com/assets/15836242/22894812/558345b0-f1e8-11e6-93a8-8ea0d9b082c6.png)

**Comment by gregorydimitriadis** [comment]
@hammondcl Is this collection file edited in the dropbox folder? I just opened it and looked at U1, and I don't see the fields for 'body lean' and 'hp: jut' - the ones where there was an out-of-bounds event.

**Comment by gregorydimitriadis** [comment]
@hammondcl Also the xml file inside the collection says that there are no events for either one of those fields defined for U1

**Comment by hammondcl** [comment]
I have no idea what happened to those.. They should still be coded. I reset the endpoints of those offsets to align with the end of the utterance a few weeks ago, but didn't delete them. How would you like me to proceed?

**Comment by gregorydimitriadis** [comment]
@hammondcl I just tested on a local version of this collection, tried adding back in those events and bringing them to the end of the utterance, saving, closing, and reopening the collection - seems to work. So I am genuinely not sure what occurred with those events initially. My best guess, since these seems related to timeframes out of bounds etc, would be that this is also related to #123 and #118 with old timeframes rendering where they are not supposed to, and should be valid to apply the same fix-as-you-go approach.
