### ISSUE TITLE
"Play Utterance" Button not playing selected utterance

### ISSUE THREAD

**Issue by geograil** [DCS-LCSR/SignStream3#121]
File: Rachel 65

I edited a gloss in utterance 10 and subsequently saved the file. I then clicked into the next utterance, and clicked the play utterance button. It did not play utterance 11, but in fact played utterance 10. 

I thought the green line may have been still in utterance 10, so I dragged it into the coding of utterance 11. I proceeded to click the button again and it still only played utterance 10. 

Then to check if it was utterance 10 or the fact that I had last edited and saved in that utterance, I went into utterance 8, edited a gloss, and saved. I clicked into another utterance, hit the button, and it would only play utterance 8.

**Comment by gregorydimitriadis** [comment]
@geograil  Can you attempt to reproduce this? I believe I know what has occurred but am not certain. When the 'play utterance' button is clicked, it does a few checks: First, it checks if you have any event/entity selected, and if so then plays the utterance it's a part of. Second, it checks if the green slider is within the bounds of some utterance, and if so then it plays that utterance. Otherwise, it will [currently it plays the entire video from time 0, but I think a better thing to do would be to do nothing at all (similar to what occurs when no entity is selected and 'play entity' is pressed)].

My suspicion is that you had an entity from U10 selected while moving the green slider around, so step 1 took precedence and it kept playing U10.

**Comment by geograil** [comment]
Hi Greg, 

I did go into the file I'm working in and try it. I think what you said is correct, but it is odd that it checks it this way. I was always with the impression that when I click the "Next Utterance" button or actually select the utterance in the left sidebar, it would de-select things in the previous utterance. It seems odd that after I do that, and even when I then drag the green slider in the utterance I want, it still defaults to the last thing edited/selected.

**Comment by gregorydimitriadis** [comment]
It's true - clicking next/prev will not de-select any entities. This is a possibly, but not the currently implemented flow. We could add that as a separate issue to look at as an enhancement?

**Comment by geograil** [comment]
Definitely! I think it would be more intuitive user wise. At least for me, when you click the next utterance button and then hit play utterance, you assume it would go with the utterance you are currently looking at. Now I know why it's doing what it's doing though, so that should help in the mean time

**Comment by hammondcl** [comment]
This is still doing it the old way and playing the utterance that you last selected something in, not the one that you're currently looking at
