### ISSUE TITLE
Clicking next/prev utterance buttons should de-select everything

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#126]
As initially referenced in #121...

"I did go into the file I'm working in and try it. I think what you said is correct, but it is odd that it checks it this way. I was always with the impression that when I click the "Next Utterance" button or actually select the utterance in the left sidebar, it would de-select things in the previous utterance. It seems odd that after I do that, and even when I then drag the green slider in the utterance I want, it still defaults to the last thing edited/selected.

It's true - clicking next/prev will not de-select any entities. This is a possibly, but not the currently implemented flow. We could add that as a separate issue to look at as an enhancement?

Definitely! I think it would be more intuitive user wise. At least for me, when you click the next utterance button and then hit play utterance, you assume it would go with the utterance you are currently looking at. Now I know why it's doing what it's doing though, so that should help in the mean time"

**Comment by gregorydimitriadis** [comment]
Whichever utterance was clicked (or moved to with the next/prev buttons) should be the operative utterance which is acted on when "play utterance" button is clicked.

**Comment by aimeeaylward** [comment]
In this latest version, clicking "Prev Utterance/Next Utterance" and then "Play Utterance," does play the utterance that you are now looking at, but it doesn't deselect the events from the previous one. For example, i tested this in Cory 113; I had selected the "oo" mouth event in utterance 45, then clicked "Next Utterance" to go to U46. When I clicked "Play Utterance," it did play utterance 46 which was now displayed in the window, but when I went back to check in U45, the "oo" mouth event was still selected. However, since it now plays the correct utterance I'm not sure the deselecting would be important, just something I thought to mention anyways.

**Comment by aimeeaylward** [comment]
To add to my previous comment, clicking "Play Utterance" twice in a row doesn't work. The first time using the "Play utterance" button works, but if you click the button after it finishes playing through the utterance once, it doesn't play through again until after you have moved the vertical green bar.

**Comment by cneidle** [comment]
1. The issue of what happens when you scroll beyond the selected utterance, but, with the utterance still selected, you click on "play utterance", which we discussed previously, has not yet been resolved.  The behavior should be that "play utterance" plays the selected utterance.  Right now nothing happens. (You would have to select another utterance, then reselect the first one, in order to play that selected utterance).

2. I agree that "next utterance" (or "previous utterance") should cause the next (or previous) utterance to be selected; and the utterance that is no longer being viewed should be deselected.  That would be the expected behavior.

3. And I am experiencing the same problem reported by Aimee -- you should be able to invoke "play utterance" more than once.  

4.  There is also the issue of what should happen when multiple utterances are viewed in the window, and therefore also selected on the left.  I know we discussed this a while back.  Right now it seems to play the utterance in which the currently active frame is located, which makes sense, so that seems fine.  (I know we had talked about different highlighting for the active utterance in such cases, which would be ideal, but would be a low priority item at this point.)

**Comment by gregorydimitriadis** [comment]
Currently the logic of the play utterance button is this:

If there is a selected event, play the utterance which encapsulates that event.
Else: If the green slider is within the bounds of an utterance, then play that utterance.
Else: Do nothing

It could be that after playing through the utterance, the slider is just outside the bounds of the utterance in your collection (just based coincidentally on the timing of the utterances/etc). And then nothing would occur.

The change made for this issue was to de-select everything in the current utterance when either prev/next or selecting a new utterance occurred - this apparently is working, with the exception as Aimee pointed out that nonmanual events do not get de-selected. I'll fix that easily enough.

It's possible to add a third if-condition check to the logic above: which would be if the green slider is out of bounds, but we still have something selected on the left, we can play that utterance. But then the wrinkle arises of what happens with multiple things selected (because they're all simultaneously visible) - what should occur in this case?

**Comment by cneidle** [comment]
My understanding was that the “selected utterance” is the one
that is highlighted at the left.  It is normal for highlighting to provide 
a visible cue as to what is selected, and therefore to be acted
upon by a button, e.g.

So, if the slider is out of range of the utterance (which it shouldn’t
be, by virtue of the “play utterance” button having been invoked),
but that utterance remains selected (i.e., highlighted), then the
expectation would be that “play utterance” would play the highlighted
utterance.

If the scrolling (in the gloss window) results in a new utterance 
becoming visible, then that new utterance would be highlighted, 
and the previous utterance deselected.

The suggestion we had discussed some time back, for the case where
multiple utterances are visible, and therefore, highlighted, on the left,
was to have the highlight appearance be distinctive for the one 
utterance that contains the current frame.  That would be the
utterance that would also play when “play utterance” is invoked.

If the slider is in between utterances in that case, then “play utterance”
should do nothing because there is no selected utterance.

That is my sense, anyway, of what would be desired…

I guess this becomes more complicated with multiple segment tiers,
as the slider could be within two utterances having different start and
end points.  I guess the determination could be made based on which
of the two windows is active.

what do you think ??

**Comment by cneidle** [comment]
This is listed as complete, but it does not seem to be fixed.  If I have something selected in a given utterance, e.g.

![screen shot 2017-10-12 at 3 05 43 pm](https://user-images.githubusercontent.com/13629122/31514205-da314878-af5e-11e7-94e1-6dcd9fc52656.png)

And I go to a different utterance, either by clicking on a different U in the left, or by using the Next or Previous button, and i then go back to that utterance, what was selected before is still selected.

**Comment by gregorydimitriadis** [comment]
True - this is still incomplete. Adding to current the current cycle.
