### ISSUE TITLE
Edit the text in the menubar

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#135]
Text should say "(Re)name Participant" and "(Re)name Segment Tier"

**Comment by aimeeaylward** [comment]
This has been changed in the latest version.

**Comment by gregorydimitriadis** [comment]
Thanks Aimee. I will close this shortly.

**Comment by cneidle** [comment]
Low priority:  Since the pane that has the information about temporal partitions and segment tiers is not resizable (which would be the ideal), it would be great to make it at least a little bit wider, since it is very difficult to see the names.  

This is not at all critical, however; low priority relative to other issues.

![screen shot 2017-06-07 at 12 44 13 pm](https://user-images.githubusercontent.com/13629122/26890339-3594cb48-4b7f-11e7-95f0-7b2c73bd2833.png)

**Comment by gregorydimitriadis** [comment]
@cneidle closing this issue out and spinning off this resizing to another issue - #139
