### ISSUE TITLE
Problem with Final Holds

### ISSUE THREAD

**Issue by blazetravis** [DCS-LCSR/SignStream3#15]
The latest version of SignStream is having problems with setting final holds on main glosses.

When opening the new sign stream, I followed these steps to get to the problem:
1. Open UAT.
2. Go to Utterance 50.
3. Control click the gloss WITH+
4. Select final hold.
5. Get "Warnig message"
6. Press ok.
7. Get display as seen below:
![screen shot 2015-08-03 at 4 48 32 pm](https://cloud.githubusercontent.com/assets/13489587/9047422/d0ddded4-39ff-11e5-8cab-607965ed498c.png)
1. Try to set the final hold anyway.
2. Get another "Warnig message"
3. Press ok.
4. Get display as seen below:
   ![screen shot 2015-08-03 at 4 49 56 pm](https://cloud.githubusercontent.com/assets/13489587/9047431/e28a9b86-39ff-11e5-9114-37ca6ad1cd03.png)

**Comment by gregorydimitriadis** [comment]
This is a problem for all "associated elements" and handshapes, in general. Behavior should be similar for all, such that adding or deleting any of them in one gloss is reflected in the other glosses as well.

**Comment by kwasiopoku** [comment]
Hi @blazetravis could you kindly send me the database for this error message via email?

Thanks much.

**Comment by blazetravis** [comment]
Hey!

Sorry I wasn't in the office at that time today, and I won't be again until
Monday unfortunately. However, you could email Carol or Rebecca and I'm
sure they could get it to you sooner.

Thanks,
Blaze

**Comment by cneidle** [comment]
Blaze,

What file is this?

Am I missing something?  I don’t see information about what file this is…

thanks,
 Carol

**Comment by blazetravis** [comment]
Hello,

I believe this issue was happening regardless of the the file being used. But when I submitted this, I was working with the _CORRECTION_ Cory 112 file.

Blaze

**Comment by kwasiopoku** [comment]
@blazetravis With the latest version of SignStream3, we are able to re-produce some of the behavior that you reported but unfortunately not exactly as reported.  Are you in the office at all today or tomorrow?  I will like to schedule a 15 minute call with you to walk through this use case.  

Thanks.

~Augustine

**Comment by blazetravis** [comment]
Hello,

No, unfortunately I will not be in office tomorrow. I could potentially
come in on Friday around 1pm?

Blaze

**Comment by cneidle** [comment]
Thanks, Blaze,

Let’s see if Rebecca will be able to figure out what you
have been experiencing and demo it for Gregory and
Augustine…

If not, and if they would be available on Friday at 1, that
might be very helpful.

If there’s anything that you could usefully communicate to
Rebecca to increase the chances that she would be able
to reproduce the problem, that would be great!

THANKS,
 Carol

**Comment by gregorydimitriadis** [comment]
Adding the expected behavior/rules of locking glosses that Augustine laid out separately via email:

Initial and Final Holds
Adding final holds on a locked glosses should result in addition to both gloss 1and gloss 2.  Right and left hand shapes should align with the end of the final hold
Deleting final holds on a locked glosses should delete from both gloss 1 and gloss 2.  Right and left hand shapes should readjust back to align with end frame for the gloss
Adding final holds on an unlocked glosses should result in addition only to the gloss in question.  The corresponding hand shape should be re-align with the end of the final hold for it’s associated gloss
Deleting final holds on an unlocked glosses should delete from the gloss in question.  The corresponding hand shape should readjust back to align with end frame of it’s associated gloss
The same behavior apply to initial holds

Onsets and Offsets
Adding Offsets on a locked glosses should result in addition to both gloss 1and gloss 2.  Right and left hand shapes should remain aligned with the end of the main gloss
Deleting Offsets on a locked glosses should delete from both gloss 1 and gloss 2.  Right and left hand shapes should remain aligned with the end of the main gloss
Adding Offsets on an unlocked glosses should result in addition only to the gloss in question.  Right and left hand shapes should remain aligned with the end of the main gloss
Deleting Offsets on an unlocked glosses should delete from the gloss in question.  Right and left hand shapes should remain aligned with the end of the main gloss
The same behavior apply to initial holds

**Comment by blazetravis** [comment]
Exactly. Thanks!

**Comment by gregorydimitriadis** [comment]
Just curious - when was the last time all the above behavior of associated elements worked as expected?

**Comment by blazetravis** [comment]
The June version that I'm still working with was (mostly) fine for main
glossess

**Comment by gregorydimitriadis** [comment]
Blaze,
Please clarify what should occur in each of these situations:

Situation A) (described for final holds, but also apply same situation to initial holds)
1) Add a final hold to a locked gloss; see the handshapes align to the end of the final hold
2) Add an offset to the locked gloss; see the handshapes keep aligned to the end of the final hold
3) Delete the final hold from the locked gloss; see the handshapes realign to the end of the main event
4) What occurs with the offset?

Situation B)
1) Unlock right-left from gloss1
2) Add an offset to gloss1
3) Lock gloss1 between right-left
4) What occurs with gloss2 - does it now have an offset?
(situation also applies if deleting the offset while unlocked)

Situation C)
1) Unlock gloss-phon from gloss1
2) Add a final hold to gloss1
3) Lock gloss1between gloss-phon
4) What occurs with the right-hand gloss - does it now align to the end of the final hold?

**Comment by blazetravis** [comment]
Situation A)
1) Add a final hold to a locked gloss; see the handshapes align to the end
of the final hold _RIGHT_
2) Add an offset to the locked gloss; see the handshapes keep aligned to
the end of the final hold _WE DO NOT ADD OFFSETS TO MAIN GLOSSES_
3) Delete the final hold from the locked gloss; see the handshapes realign
to the end of the main event _RIGHT_
4) What occurs with the offset? _WE ONLY USE OFFSETS FOR NONMANUALS_

Situation B)
1) Unlock right-left from gloss1
2) Add an offset to gloss1
3) Lock gloss1 between right-left _THERE IS NO NEED TO RE-LOCK THEM.
UNLOCKING THEM ALLOWS US TO MANIPULATE ONE AT A TIME_
4) What occurs with gloss2 - does it now have an offset? _IT SHOULD NOT,
BUT AGAIN WE DO NOT USE OFFSETS/ONSETS FOR MAIN GLOSSES_
(situation also applies if deleting the offset while unlocked)

Situation C)
1) Unlock gloss-phon from gloss1
2) Add a final hold to gloss1
3) Lock gloss1between gloss-phon
4) What occurs with the right-hand gloss - does it now align to the end of
the final hold? _YES_

**Comment by blazetravis** [comment]
Wow this one is the most impressive bug fix yet. I was relentless in trying to get it to malfunction.. but it looks to be fixed!

Great work guys. I can now use the UAT as a viable version of SignStream for main gloss work, instead of the old June version.

This bug is, at last, fixed.

**Comment by cneidle** [comment]
YAY !!!

And thanks so much, Blaze, for staying late today
to test the program !

best,
 Carol

**Comment by gregorydimitriadis** [comment]
Thanks! Closing this out.

**Comment by kwasiopoku** [comment]
Thanks Blaze!

~Augustine
