### ISSUE TITLE
Play utterance goes beyond the end of the utterance

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#173]
I'm looking at File 111, U3

Go to end of utterance gives a correct result.

Play utterance ends beyond the last frame of the utterance, however.

<img width="1143" alt="screen shot 2017-08-21 at 7 57 52 pm" src="https://user-images.githubusercontent.com/13629122/29542918-46943372-86ab-11e7-81c8-d43155f87488.png">
<img width="1119" alt="screen shot 2017-08-21 at 7 57 38 pm" src="https://user-images.githubusercontent.com/13629122/29542919-46999628-86ab-11e7-81bd-bffb166bee5b.png">

**Comment by gregorydimitriadis** [comment]
@cneidle How many frames beyond the end of the utterance does 'play utterance' go?

**Comment by cneidle** [comment]
One frame beyond.

But in many cases, that means seeing black instead of seeing the person
from the utterance.

thanks,
 Carol

**Comment by cneidle** [comment]
This same problem occurs with "play event" and "play entity" : Rather than ending on the final frame of the event or entity, the active frame when the play is over is one beyond where it should be:

<img width="980" alt="screen shot 2017-08-23 at 4 32 58 am" src="https://user-images.githubusercontent.com/13629122/29606473-6bcad508-87bc-11e7-8dba-3654a677b1ca.png">

**Comment by cneidle** [comment]
What I reported above doesn't happen all the time.  I'm not experiencing this problem now.  Not sure what determines when/whether there will be "overshoot" on playing events.

**Comment by gregorydimitriadis** [comment]
@cneidle The reason for this is that not all events/utterances use frames the same way. Some of them have frame numbers which are divisible by the "packet duration" used for the movies (which is the correct way to do it, which was not always the case - this was changed awhile ago). This applies to new events/utterances and when the start/end time is set with the menubar buttons manually. There are then "old" events/utterances which do not have frame numbers in this same way, and so when frames are calculated for playing, it goes according to the packet duration, and may overshoot the end as visible on the screen.

The best solution for this, in lieu of manually changing all the frame numbers of the old events/utterances (which I'm wary to do, because that can be very dicey) is to account for them differently than the new ones. The new ones will play through as expected, to the last frame. The old ones' end frame can be rounded down to the next nearest packet duration, and playing through it will end at that rounded down frame value, so it will stop just short of the end, as visible on the screen.

**Comment by cneidle** [comment]
Hi Greg,

Yes, that sounds OK at the utterance level.  That explains also why 
we were having this problem only sometimes.

Am concerned, though, for how this  may work for things like “play event”.
In that case, and perhaps also in the case of play utterance, might it make
sense to have these commands (however modified along the lines you suggest)
be immediately followed, behind the scenes, by a command to make the end frame 
of the event or utterance the current frame (i.e., to advance to that end frame) ??

thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle It's a good idea, but I think it may be an inappropriate place to do the correcting of the frames when it is played through. The expectation of playing should be that it only plays through, and not edit anything in the meanwhile. (The principle of least surprise, so to speak). Unfortunately the best way I can see doing that would be to correct everything in one go when the collection is opened, but that is slightly more involved, but perhaps we can roll that into a new issue to be looked at in the future.

For now, this issue can be resolved with the rounding down of the end frame to play to.

**Comment by cneidle** [comment]
Hi Greg,

Not sure we’re fully communicating.

I was not talking about editing.

I was talking about what the current (visibly displayed) frame should be
at the conclusion of a “play utterance” or “play event” action.

It should not be later than, or sooner than, the last frame of the
relevant object.

I was not talking about editing anything, only having the green scroll bar
land on the final frame of whatever it is when the play action is completed.
Anything else will look very strange.

What do you envision happening otherwise?

I just want to make sure we won’t see something like this after
“play event” for WARM, e.g.:



thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle I see. If possible for the green scroll bar to be "in between" what it thinks of as the proper frames while displaying normal to the user's eyes, then we can do that as well.

**Comment by gregorydimitriadis** [comment]
Closing as fixed as per Carol on 2017-09-06
