### ISSUE TITLE
Onsets cannot be 1 frame

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#18]
While in the nonmanual section of SS3, I cannot make onsets be only one frame away from the start of an event. A "WARNIG" message appears.

**Comment by rklopez** [comment]
I found this bug is not fixed. If I delete the onset and re add it, it will be one frame. However, if I make it longer and then try to return it to one frame, a warning message appears. I know that when I closed this it seemed the issue was fixed, I'm not sure why the bug has returned. 

![screen shot 2015-08-21 at 10 50 56 am](https://cloud.githubusercontent.com/assets/13489569/9411250/e94f7aa8-47f2-11e5-80db-478de32bbd5a.png)

**Comment by gregorydimitriadis** [comment]
@rklopez What are the frame numbers for the event in this picture?

**Comment by rklopez** [comment]
00:12:29;28

On Fri, Aug 21, 2015 at 10:57 AM, Greg Dimitriadis <notifications@github.com

**Comment by gregorydimitriadis** [comment]
@rklopez Sorry, I meant the frame numbers in the toolbar at the top, next to the -/+ and "Set" buttons.

**Comment by rklopez** [comment]
Sorry! 22500020 and 22501021

On Fri, Aug 21, 2015 at 11:02 AM, Greg Dimitriadis <notifications@github.com

**Comment by gregorydimitriadis** [comment]
@rklopez Thanks for that. This issue is fixed as you originally noted, but it is only for newly added events/bars in the nonmanual section. For pre-existing events (meaning they existed before the new version of SS UAT) the issue may still arise. There is, however,  a solution in this case for this event and also if it occurs in the future again:
Try to set the start or end of the event itself (depending on which side the error is occurring) using the "Set" button, and then adding the onset and trying again to make it one-frame.

**Comment by rklopez** [comment]
Well, if I'm adding the onset from scratch, it automatically sets to one frame, so there's no need for the set button use. It's only when I try to edit it back to one frame the the problem arises. So, I'll just delete and re add the onset if I need it to be one frame for pre-existing events.

**Comment by rklopez** [comment]
Bug will be present on pre-existing events.
