### ISSUE TITLE
U1 disappears

### ISSUE THREAD

**Issue by rklopez** [DCS-LCSR/SignStream3#22]
After using SS3 for an extended period of time, U1 does not appear when you open it. 

![screen shot 2015-08-05 at 3 48 16 pm](https://cloud.githubusercontent.com/assets/13489569/9096181/9e275714-3b89-11e5-868d-74136046b463.png)
![screen shot 2015-08-05 at 3 48 42 pm](https://cloud.githubusercontent.com/assets/13489569/9096182/9e27a0e8-3b89-11e5-84c1-c2313b9f1b9f.png)

**Comment by blazetravis** [comment]
This bug is fixed.

**Comment by blazetravis** [comment]
Hm. For some reason when Chris and I were playing around with SignStream today, this bug popped back up.

Steps to reproduce are a little foggy because I was not expecting it at all:
Go to utterance 2 in a Rachel file.
Click on fields.
Add a random field.
Populate it with a non-manual.
Label the non-manual.
Edit existing main glosses.
Click out of utterance.
Go to U3.
Drag cursor back and forth.
Play the entire utterance.
Click out of utterance.
Attempt to click into U1.
See above bug reproduced.
