### ISSUE TITLE
Overlap that should not be allowed - gloss items - est. 8 hours

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#223]
I'm working with file 112, which I emailed you very recently -- utterance 82.

The endpoint of one sign (GROUP/TOGETHER) overlaps with the initial hold of the following sign.
This should not be allowed...

<img width="713" alt="screen shot 2018-06-06 at 2 10 10 pm" src="https://user-images.githubusercontent.com/13629122/41056894-9146a3ac-6993-11e8-9f5f-f316643d70a9.png">

I just deleted that initial hold, and I am (correctly) no longer allowed to add a hold, because it would involve disallowed overlap. So perhaps this is a holdover from an older version of the program that did not enforce things properly.  Just letting you know, in any case.

**Comment by bugspotter33** [comment]
Issue is still occurring. I found an example in Rachel file 66 U1 all the glosses have overlap!!! It doesn't matter if they are one handed or two handed. This issue is also occurring through utterances 1 and 2


![screen shot 2018-07-09 at 11 34 07 am](https://user-images.githubusercontent.com/38887034/42460539-215a8368-836c-11e8-8937-b0791de96e1b.png)

![screen shot 2018-07-09 at 11 34 39 am](https://user-images.githubusercontent.com/38887034/42460542-238b6116-836c-11e8-9267-39352b29bdb4.png)

![screen shot 2018-07-09 at 11 34 56 am](https://user-images.githubusercontent.com/38887034/42460544-25182df2-836c-11e8-9f1f-2960dc91a92c.png)

I went through the file and the glosses that have an overlap of both words and handshapes seem to have a more specific display where one line of the gloss is darker than the rest almost appearing to be bolded. However if the gloss has an overlap in handshapes only, it isn't clear as to which ones has this issue and which ones do not. See below for handshape overlap. 

![screen shot 2018-07-09 at 11 58 38 am](https://user-images.githubusercontent.com/38887034/42461905-c0cb42d6-836f-11e8-98f1-6cf12a118cca.png)
![screen shot 2018-07-09 at 11 58 47 am](https://user-images.githubusercontent.com/38887034/42461908-c233d28c-836f-11e8-9738-5eaed4435cdf.png)

**Comment by cneidle** [comment]
The above case is a bit different from the first reported issue.  This is a case where there is a 2-handed sign glossed.  When that is deleted, it reveals the presence of a similarly glossed 1-handed sign on the non-dominant hand, which cannot be deleted.  I tried first making the 2-handed sign into a 1-handed sign on the dominant hand.  What is on the non-dominant hand still cannot be deleted.  Indya is finding this occurring with other signs in this file.  She is about to report another such problem.  Seems we cannot continue working with this file until the issue is resolved...  i.e., this is a serious bug.  Thanks!

**Comment by bugspotter33** [comment]
Found another example of this issue in Cory 108 U17 with the gloss BOX/ROOM and then there is something weird happening with the display on ARRIVE. So I am going to delete it and enter it in again. 


![screen shot 2018-07-17 at 1 46 14 pm](https://user-images.githubusercontent.com/38887034/42836157-45a2861e-89c8-11e8-9a85-9d81744ebd98.png)


![screen shot 2018-07-17 at 1 46 29 pm](https://user-images.githubusercontent.com/38887034/42836169-493af8ce-89c8-11e8-9c6b-d6304293afbf.png)

**Comment by cneidle** [comment]
increasing priority level

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

sign overlaps were rechecked and corrected.  Issue likely no longer exists.

Closing.
