### ISSUE TITLE
SS3 looses participant and annotators when saving and reopening a collection.

### ISSUE THREAD

**Issue by kwasiopoku** [DCS-LCSR/SignStream3#24]
When you save a collection with participants and annotators the selected data is lost when the collection is reopened

**Comment by blazetravis** [comment]
This is fixed. However, once a participant/annotator is selected, they cannot be changed or removed.

**Comment by kwasiopoku** [comment]
@blazetravis do you mean the selection on the Temporal Partition 1 Menu at the bottom of the Gloss Window?

**Comment by blazetravis** [comment]
@kwasiopoku No. I mean in the macro unit. I went back to edit the macro unit to see if I could change the annotator/participant after SignStream saved the information I input before the collection was restarted. It saved the information I input just fine, but I couldn't EDIT or REMOVE either annotator or participant.

**Comment by kwasiopoku** [comment]
@blazetravis I see what you mean.  Thanks for raising this issue.

**Comment by kwasiopoku** [comment]
This ticket has unresolved components that were identified in UAT.  The remaining issues will be addressed in Sprint 2

**Comment by blazetravis** [comment]
Currently, the annotator and participant drop-downs are non-selectable. This bug is impossible to test right now.

**Comment by gregorydimitriadis** [comment]
Is this even after adding annotators and participants through the "Macro Unit Information" screen?

**Comment by blazetravis** [comment]
So currently I am allowed to edit in the Macro unit. Adding new participants and annotators works just fine.

However. In the participant section, I am never allowed to delete the first participant I add (subsequent participants added can be deleted easily). The delete button does not work for the first participant.

![screen shot 2015-10-27 at 1 42 03 pm](https://cloud.githubusercontent.com/assets/13489587/10767039/9ce2f3a0-7cb0-11e5-927a-8fc0995a409e.png)

In the annotator section, I AM allowed to delete the first and subsequent annotators. BUT when I go to select them in the annotating window, the "select" button next to annotator does not work. So no names are displayed. I AM able to select the participant here. Weird.

![screen shot 2015-10-27 at 1 42 23 pm](https://cloud.githubusercontent.com/assets/13489587/10767047/a6032978-7cb0-11e5-8d9f-4f1334658066.png)

Even WEIRDER is that when I save and exit, which was the original intent of this thread, EVERYTHING is saved. So, this bug is... sort of fixed. I can now click on everything in the annotating window:

![screen shot 2015-10-27 at 1 44 59 pm](https://cloud.githubusercontent.com/assets/13489587/10767146/2bae8fc2-7cb1-11e5-92ee-545f0cb1cffe.png)

But, in the edit macro unit, things were just as they were before I saved, exited, and reopened:

![screen shot 2015-10-27 at 1 42 03 pm](https://cloud.githubusercontent.com/assets/13489587/10767160/3d32bc1e-7cb1-11e5-91ce-155b12973825.png)

**Comment by gregorydimitriadis** [comment]
The ones which are greyed-out are like this because they are currently selected from a dropdown inside any of the utterances.

In the case where you just added the first participant, I believe it automatically selects this one, and so it greys it out.

And the dropdowns will not be updated unless you go to the presentation view and then shift-click back into the utterance so that it reloads with the fresh list of annotators/participants.

**Comment by blazetravis** [comment]
Then this issue is fixed.
