### ISSUE TITLE
Sign type field

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#263]
Create a new manual field for sign type (e.g. lexical, fingerspelled, loan) which displays as part of a gloss

**Comment by gregorydimitriadis** [comment]
Hi @cneidle - we've been thinking on this one recently on our side. If we had an additional field (under the existing gloss1/gloss2/handshapes and future location field) how would we expect this to function? 

Would it always 'sync' to the dominant hand of the gloss? If there is a gloss with only the nondom hand used, should it sync to that hand instead in this case? (So default, use the dom if it is available, otherwise use nondom).

What about cases like the attached, where you have two overlapping glosses, one for dom hand and one for nondom hand -- what would you like to show up in the sign type field, as technically 2 types would be overlapping here?

![Screen Shot 2019-07-24 at 12 04 16](https://user-images.githubusercontent.com/847197/61809468-5aa2c200-ae0b-11e9-9909-f51e5804868c.png)

**Comment by cneidle** [comment]
Hi,

Good question.

I think we will probably need to have two fields for location, one above the other:

a top line for the location associated with the dominant hand of a 1-handed sign
produced with the dominant hand or with the dominant hand of a 2-handed sign;
and a second line below, used only for the exceptional cases of 1-handed signs
produced on the non-dominant hand.

The handshape information for FATHER and nondomgloss in your example below
would be entered separately, with distinct morph-peon wondows both for handshapes
and for location.  

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Hi @cneidle just to clarify - when you say 'location' you mean 'sign type' - right?

**Comment by cneidle** [comment]
Sorry- I misread your question.  I thought you were asking about how to represent LOCATION in the case where there are two overlapping items associated with a location.  So that is the question (which you didn't ask) that I was responding to.  This is an important modification of the way in which we had been thinking of the location field.

The same issue does also arise for sign type.  And the principle would be the same:  the main field would align with the dominant hand gloss for a 1-handed sign produced on the dominant hand or a 2-handed sign, whereas the additional extra field would be used only for 1-handed signs produced on the non-dominant hand.

So:     

         GLOSS1________
                    fs-GLOSS2_________

          ----4head-----
                   ---off-the-body---

          Lexical
                    Fingerspelled

**Comment by douglas-motto-at-rutgers** [comment]
As of SignStream4_4.0.0_convergence_2021_05_06_1324_def1fe17

done.

Closing.
