### ISSUE TITLE
Additional Segment Tier functionality

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#31]
Segments must also have the capability to do the following things:
- Must be able to click-into an individual segment (and display the glosses for just that segment) in the same manner as we can currently click-into an utterance from the Temporal Partition line (which would display the glosses for every segment under that utterance)
- Once we have already clicked-into the utterance from the Temporal Partition line, we must also be able to hide individual segments from view. For example, if under some utterance named U3 there are 5 segment tiers, and after clicking-into U3 on the Temporal Partition line all 5 segments in that column are displayed one on top of the other, we should be able to somehow hide segment tiers 3, 4, and 5 to just leave segment tiers 1 and 2 visible.
- Must also be able to rename individual segments. For example, all segments under some utterance named U3 are also currently labeled U3 as well - but we should be able to edit the names for each segment on their own.
- Segment ordering: new segments should be added to the bottom of the viewing list, and should stay there throughout and beyond the current session. The same ordering should apply when in the gloss window (looking at multiple segments) as well.

**Comment by cneidle** [comment]
Right - A more realistic use case is that you have two segment tiers.  It should be possible to hide one or the other (but not both, since at least one must be visible!).  So, suppose there are two segment tiers defined, you should be able to open both by clicking (in the appropriate way) on the Utterance level unit.  
And then you could hide one by clicking on the "hide segment" button.

You should be able to open any specific segment and only that segment, by clicking on it within the segment tier from the higher level (as you describe above).   If you have one segment displayed but there are others that exist, there should be an option to "display other segment(s)" rather then to "hide segment".

**Comment by gregorydimitriadis** [comment]
Just a note for myself on progress with these issues:
The only one not specifically coded so far is the ability to click into a specific segment from the Overview Window and then display only that segment in the Utterance Window.
