### ISSUE TITLE
Signbank display

### ISSUE THREAD

**Issue by bugspotter33** [DCS-LCSR/SignStream3#336]
I was searching for a sign and what was displayed was completely wrong but when I clicked on the  examples the correct examples were displayed. 

![Screen Shot 2020-03-26 at 1 12 00 PM](https://user-images.githubusercontent.com/38887034/77692370-bb1e6c00-6f63-11ea-9c72-7b6e6873573f.png)

**Comment by gregorydimitriadis** [comment]
@bugspotter33 was this from the SignStream sign bank or the online DAI?

**Comment by bugspotter33** [comment]
Similar issue when trying to play video of an example of a sign searched, the video displayed is wrong when in SS searching the signbank.
Ask-1p, Ask_2-3p-pl-arc, 1p-Ask:j, 2p-Ask:j all the display videos for this sign is wrong. 

![Screen Shot 2020-03-26 at 1 20 16 PM](https://user-images.githubusercontent.com/38887034/77693159-2288eb80-6f65-11ea-87db-b087ea819e01.png)
![Uploading Screen Shot 2020-03-26 at 1.23.37 PM.png…]()

**Comment by cneidle** [comment]
Hi Indya,  

You have found a major problem with the Sign Bank.  In general, please
report these in bugs in the SIgn Bank rather than the SignSteram project.

Augustine reuploaded the continuous signing data very recently, and
something seems to have broken with respect to the Sign Bank connection...

I'll let him know.  Thanks.

**Comment by douglas-motto-at-rutgers** [comment]
Closing this as should be a DAI issue.
