### ISSUE TITLE
Sign Type - inserting from Sign Bank / modifying setting in Morph/Phon window

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#363]
I am checking a file where a number sign was classified as a lexical sign.

If I try to enter all information from the sign bank, the sign type is not included.

If I try to modify the sign type of the entry itself, I get a message warning me that it will wipe out the handshape information (since it seems that the default setting for numbers is 1 hand; so it will wipe out the information about the 2 hands).  Once it has wiped out the handshape information and Number is checked, I can then enter the handshape information from the Sign Bank and the Number setting remains, so I end up with the right result.  But this is obviously not what should be happening.  This is consistent behavior.

**Comment by gregorydimitriadis** [comment]
@cneidle Hi Carol - first a question(s):

Was the number sign mis-classified as lexical - in the sign bank display? 

Then, when you did the 'add to' it was not included - what was the sign type in the MorphPhon prior to this? And afterwards, did it change?

The warnings, I think are intentional when you go from 2-handed to 1-handed.

**Comment by cneidle** [comment]
Hi Greg,

I sent you screenshots showing that the Sign Type was listed in the
sign bank as “N/A” if I remember correctly.

The sign type was lexical (the default) after insertion of the information
about a number sign in the Morph-Phon window.

Yes, I understand what is happening with the 2-handed change.  The 
inconvenience I described is collateral damage in this case from the 
inability to include the “Number” classification when information is entered
from the sign bank.  

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
@cneidle I see - what was the gloss in this case? - thanks

**Comment by cneidle** [comment]
Here's an example.  This happens, so far as I can tell, with all Number signs in the sign bank.  Thanks.

<img width="954" alt="Screen Shot 2020-08-24 at 10 31 09 AM" src="https://user-images.githubusercontent.com/13629122/91057289-001efb00-e5f5-11ea-896d-830946d19c4a.png">

**Comment by gregorydimitriadis** [comment]
@cneidle after reading this carefully again, I think the issue is with the sign bank. I don't see any entries in the sign bank itself for SIGN_TYPE of "NUMBER" -- there are many entries in the file like so:

`        <SIGN_TYPE></SIGN_TYPE>`

which makes the sign type show up as 'n/a' in the window.

**Comment by cneidle** [comment]
I confirmed with Augustine that, for some reason, the sign types were not included in the Sign Bank.  He will fix this before hte next Sign Bank is released.  Thanks!
