### ISSUE TITLE
No prompt to save work before quitting

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#498]
<img width="928" alt="Screen Shot 2022-04-02 at 8 24 34 AM" src="https://user-images.githubusercontent.com/13629122/161383217-519c614a-e5cf-4d6a-8030-a89280005b21.png">

**Comment by douglas-motto-at-rutgers** [comment]
Believe fixed in SignStream3-3.4.0_pre_2022_04_04_1647_dd5956a3

Will only prompt if change is detected.  If making change and still not seeing "save" dialog, comment as to what change was made.  It might not be detected properly as a change.

**Comment by cneidle** [comment]
I would not have reported this if no change had been made! For example, I open an older file, change the endpoint of a gloss, choose Quit SignStream from the menu.  It quits with no warning.  Same if I create a new file in the new version.  Add an utterance and a gloss.  Save.   Extend the endpoint of the gloss.  Quit.   No warning.

**Comment by cneidle** [comment]
Same effect by adding handshapes to a gloss, and then quitting.  Here I added handshapes to the first gloss, added the second gloss, added handshapes to that.  Then quit.  No message.

<img width="1387" alt="Screen Shot 2022-04-05 at 11 39 26 AM" src="https://user-images.githubusercontent.com/13629122/161792221-7455103b-1685-473b-8070-a88b1e4e1aa0.png">

**Comment by douglas-motto-at-rutgers** [comment]
I am not claiming that it did work in the **April 1st** version you tested.  That version is SignStream3-3.3.7_pre_2022_04_01_1131_138a09a4 and it did not work in that version as you reported.

I am claiming that I believe it is now fixed in the **April 4th** version which is SignStream3-3.4.0_pre_2022_04_04_1647_dd5956a3.  I just retested your two examples, and I am reconfirming they are fixed in the April 4th version.
