### ISSUE TITLE
Require participant selection when "New Segment Tier" is select

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#59]
- It should query the user for which Participant should be associated with this segment tier
- A dropdown of available participants should be displayed for this purpose (similar to what is now being done to select an annotator on application startup)
- The name the user picks (from the list) will be appended to the beginning of the normal segment tier name – e.g. “Jeff:Segment Tier 3”
- Also need ability to pick a different participant at any point

**Comment by blazetravis** [comment]
This enhancement is working.

But perhaps we don't want it to say "Don't see **your** name?" because we are selecting participants, not ourselves.

![screen shot 2016-02-18 at 10 48 54 am](https://cloud.githubusercontent.com/assets/13489587/13148956/6240444c-d62d-11e5-9ea0-8354901f8ee1.png)

Thanks!

**Comment by gregorydimitriadis** [comment]
That's a good catch, thanks. I'll edit that to something different in the next release.
