### ISSUE TITLE
patches ?

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#643]
I tried, from the current release version, to "update SignStream."

Got a message about patches.  ??

I disallowed installation of the patches (Bitdefender asked for permission, which I denied), but what is this?

<img width="787" alt="Screen Shot 2023-02-07 at 12 20 49 PM" src="https://user-images.githubusercontent.com/13629122/217317908-e3f49ce5-97cf-4854-a24c-c86216774f41.png">

**Comment by gregorydimitriadis** [comment]
Patches are something we started doing with the update scripts some years back. We have patch files (for the scripts mostly) so that we can use updated/bugfixed script code for already released versions of SignStream. So the patches are intentional and ensure the update process proceeds correctly and without error.

**Comment by cneidle** [comment]
Thanks for the explanation.  We have so far never recommended that users use the Update menu function, so I never saw this.  What if you install the patches but don't go through with an update?  e.g., if the version is already at most current version.  I assume that no harm is done?  thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle Yes, no harm would be done in this case. The patch files just state that the app was patched to that patch version, so that if update were to be called again, it would not need to re-download and apply the same patches again.

Closing this issue as it's not really a bug/feature/anything. We can continue discussing it here though.
