### ISSUE TITLE
Files saved in 3.3.6 also having issues with same/diff dom/ndom and start/end values when re-opened

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#680]
Doug brought to my attention that files saved in 3.3.6 also have issues when opened in the latest pre-release for 3.4.1. Specifically issues involving the values for: same/diff dom/ndom, same/diff start/end both hands, same/diff start/end dom hand/ same/diff start/end ndom hand.

This is similar to https://github.com/DCS-LCSR/SignStream3/issues/622
But given that version 3.3.6 is an older collection xml version, it uses a different validation process which the above issue does not address.

**Comment by cneidle** [comment]
Oh goodness.

Yes, I just opened a file previously saved in version 3.3.5 (as almost all of our
data has been), and this same issue does indeed occur in the latest pre-relaease
version.





Why is this information preserved when opened in 3.3.5 but lost when
opened in your latest pre-release version ?

Do you have a solution in mind?

Thanks,
  Carol

**Comment by cneidle** [comment]
Possibly naive comment/question:  I was assuming that the problem we discovered involved the current release version failing to store the Morph-phon information properly.  But since we know that the information is stored in 3.3.5 (and persists when files are opened in 3.3.5), then perhaps the problem is with retrieving the information rather than the way It is stored ??  

In any case, this raises the urgency of the loss of information about (2h)alternating signs.  It would have been bad enough to lose that information for all data annotated with 3.4.0.  But to lose that information for ALL of our data would be really problematic.

I hope you can figure out how to retrieve the information that is there.

Thanks very much.

**Comment by gregorydimitriadis** [comment]
Released in 3.4.1
