### ISSUE TITLE
Field Selector and other buttons in that region are not visible when Non-manual fields are hidden

### ISSUE THREAD

**Issue by cneidle** [DCS-LCSR/SignStream3#708]
<img width="1134" alt="Screen Shot 2024-07-12 at 2 47 10 PM" src="https://github.com/user-attachments/assets/5afba317-de6c-4509-8cb8-2759b03292c4">

-----

<img width="1241" alt="Screen Shot 2024-07-12 at 2 48 04 PM" src="https://github.com/user-attachments/assets/35ae75e0-15b6-4310-92ee-eed00e0a6694">

====

ALSO - trying to set the index to the gesture Dom field is not working

<img width="1434" alt="Screen Shot 2024-07-12 at 2 49 23 PM" src="https://github.com/user-attachments/assets/7688a4ed-b664-480c-ba66-3909c2e9a931">

-----

<img width="1244" alt="Screen Shot 2024-07-12 at 2 49 30 PM" src="https://github.com/user-attachments/assets/061122de-0237-4598-af15-12d0bd2e8383">

**Comment by cneidle** [comment]
One possibility, until this is fixed, might be to obligatorily display the non-manual fields.  They can be reduced to minimal height, e.g.:  

<img width="1263" alt="Screen Shot 2024-07-12 at 2 55 13 PM" src="https://github.com/user-attachments/assets/c8a60879-ecf9-4c0f-9f10-7e9c55d418c5">

**Comment by cneidle** [comment]
It is not right to lose access to the field-related buttons.  I hope this will be addressed, potentially in the way I suggested, i.e., by disallowing hiding of the non-manual field region until the field buttons are moved out of the region that can be hidden.

**Comment by cneidle** [comment]
One option for moving the field buttons out of the Non-manual area:

Going from:

<img width="845" alt="Screen Shot 2024-07-19 at 2 01 04 PM" src="https://github.com/user-attachments/assets/5454f9a7-af33-4591-be6a-3af7510e6491">


To:

<img width="850" alt="Screen Shot 2024-07-19 at 2 00 55 PM" src="https://github.com/user-attachments/assets/8af03434-5fc7-4037-bc6d-26ed04ce5e8f">

**Comment by cneidle** [comment]
What we really need, long-term, is for the rectangular areas in the picture below to be their own region, separate from the non-manual field region, which is not hidable.  Until that is done, it would be sufficient to make the non-manual region non-hidable.

<img width="1059" alt="Screen Shot 2024-07-20 at 10 06 15 AM" src="https://github.com/user-attachments/assets/9e381917-58e7-47da-b124-3dd4fa84a8a5">

**Comment by gregorydimitriadis** [comment]
@cneidle How about moving the button panel to above the temporal partition/segment tier selection, in the left-hand panel ?

**Comment by cneidle** [comment]
@gregorydimitriadis  Yes, that should work!  So, if I understand correctly, what you have in mind is something like this?

<img width="292" alt="Screen Shot 2024-08-07 at 1 43 35 PM" src="https://github.com/user-attachments/assets/46dcee90-65c9-4876-a1e2-3a75e6b40e75">

**Comment by cneidle** [comment]
@gregorydimitriadis  I will need to redo a few of the screenshots for figures in the documentation when a version with this change incorporated is available.  Thanks.

**Comment by gregorydimitriadis** [comment]
@cneidle I can get it looking and working like this.

<img width="834" alt="Screenshot 2024-08-08 at 18 42 30" src="https://github.com/user-attachments/assets/c28045e0-5a25-4090-9c1d-718605e4f049">

**Comment by cneidle** [comment]
@gregorydimitriadis  

That looks beautiful !   Any chance you could make the icons just a tiny bit bigger ??  Just in case it's easy... 

But wonderful.  Thanks very much.

**Comment by gregorydimitriadis** [comment]
How's this? It's the original size of the buttons before they were scrunched to fit into the previous area:

<img width="1440" alt="Screenshot 2024-08-09 at 14 24 21" src="https://github.com/user-attachments/assets/a8c3233a-f99c-44f5-9c12-54609e9cb366">

Then when the area is extended, they extend proportionally:
<img width="1440" alt="Screenshot 2024-08-09 at 14 24 48" src="https://github.com/user-attachments/assets/9bac1202-bef6-42b7-8f19-20914de839dd">

And with multiple segment tiers showing - to demonstrate the background color matches the rest of the panel:
<img width="1438" alt="Screenshot 2024-08-09 at 14 25 39" src="https://github.com/user-attachments/assets/887c798e-e6d0-49df-9a7b-3089eb1da385">

As part of this I decided to also make the bottom buttons statically sized vertically because of the loss of real estate due to the buttons on top. The widths/cutoffs I didn't change or modify.

What do you think?

**Comment by cneidle** [comment]
@gregorydimitriadis That looks terrific, Greg.  Thanks very much!
