### ISSUE TITLE
Gloss Window - handshapes for right hand disappear

### ISSUE THREAD

**Issue by gregorydimitriadis** [DCS-LCSR/SignStream3#8]
Use case: Select [two-handed + same start/end hs], click the dropdown toggle, click “same start/end hs” again.
The result is that the handshape images for the right hand disappear below

**Comment by kwasiopoku** [comment]
We will walk through this use case with Carol and her team on the expected behavior versus actual behavior.  Once the behavior is documented, we will be able to schedule this bug for a sprint

**Comment by gregorydimitriadis** [comment]
Steps to reproduce:
1) Open gloss window on any gloss
2) Select handshapes, and "Enter" out of window
3) Click back into gloss window
4) Re-select handshapes to something new
5) Again, try to re-select handshapes
6) Here, the images will disappear

**Comment by blazetravis** [comment]
This bug is fixed. 

However, I noticed a new warning message. I selected only one handshape and tried to enter out of the handshape window. The message read that I should "select more than one handshape because this gloss is more than one frame long" but this might be over-rational. In the Morph-Phon window, the "Same START/END hs" was selected, so shouldn't the program know to only expect ONE handshape, regardless of the gloss's length?

**Comment by cneidle** [comment]
Hi Blaze,

> On Nov 17, 2015, at 1:48 PM, blazetravis notifications@github.com wrote:
> 
> This bug is fixed.
> 
> However, I noticed a new warning message. I selected only one handshape and tried to enter out of the handshape window. The message read that I should "select more than one handshape because this gloss is more than one frame long”
> 
> Right.  That shouldn’t be happening… 

thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
Thanks for clarifying that. Should there be any restriction on when one handshape by itself is not allowed?

**Comment by cneidle** [comment]
Hi Greg,

As I understand, the data representation always has a start
and end handshape.

It is just that these are enforced to be the same — and only
one image is displayed — when the object is a 1-frame object.

So, if a single-frame object with one visible handshape is changed
to 2 frames, two images of the same handshape — with the setting
same start and end handshape — should be displayed
(until and unless the user changes this).  

Am I missing something here?

Thanks,
 Carol

**Comment by gregorydimitriadis** [comment]
The current data representation does not necessarily keep track of the starting and ending handshapes, but instead just keeps track of the list of handshapes and enforces exactly one for one-frame glosses.

I can definitely switch immediately to same start and end if the user moves to a 2-frame gloss.

As for the setting 'same start/end handshape' - what should occur if that changes to 'diff start/end handshape' ?

**Comment by cneidle** [comment]
Hi Greg,

Can we check with Augustine about this?

It was my understanding that there ought to be a start and end handshape
in the data representation for every gloss…

For one-frame glosses, the start and end handshape should be enforced to be 
the same and only displayed once.

This is important to be able to search for a particular handshape as the
start or end handshape.

Perhaps I misunderstood something from our last discussion about this?
it would be great to get input from Augustine.

> On Nov 17, 2015, at 2:28 PM, Greg Dimitriadis notifications@github.com wrote:
> 
> The current data representation does not necessarily keep track of the starting and ending handshapes, but instead just keeps track of the list of handshapes and enforces exactly one for one-frame glosses.
> 
> I can definitely switch immediately to same start and end if the user moves to a 2-frame gloss.
> 
> As for the setting 'same start/end handshape' - what should occur if that changes to 'diff start/end handshape' ?

I guess this is a more general question:  about what should happen if the
user changes (in any gloss) from same start/end handshape to different.

Perhaps this is something we should discuss.  Right now, as I understand it,
the settings of same/different start and end handshapes are not enforced
with respect to the actual handshape selections.

Perhaps minimally the handshape selector should open up to allow the
user to select a second handshape.  One way to ensure that the user
makes a proper selection of both start and end handshape would be
to clear the existing handshapes, but I’m not sure whether that would
be more of a help or an annoyance.  Blaze, do you have an intuition about
this ??

Thanks,
 Carol

**Comment by blazetravis** [comment]
Mmm. Well here is the confusion for me: when a fingerspelled word starts and ends with the same handshape. Certainly over the course of the figerspelled gloss, the handshapes were changing, but the start and end are the same.

Aside from this exception, the program should intuitively be expecting _more than one_ handshape inputted if "diff START/END hs" is the selected option. 

Again, aside from exceptions of Fingerspelled cases, the program should intutitvely be expecting _only one_ handshape inputted if "same START/END hs" is selected. In this case, the program should be able to populate both the start and end handshape display with the same handshape image using only one input.

**Comment by cneidle** [comment]
Hi,

For fingerspelled signs, we pay no attention to the relation between
the start and end handshape.  There is no linguistic significance
to whether or not the word happens to start and end with the same letter.

There can be any number of handshapes (greater than or equal to 1).

Whenever there is a single handshape — regardless of the category of the
sign —  that handshape serves both as the start and end handshape.  
These need to be represented separately, for purposes of searching.  
So, if there is a single ‘B’ handshape, a search for start handshape = B 
and for end handshape = B ought to find that gloss, whether the gloss 
consists of one or more frames.

The problem arises in the enforcement of same vs. different start/end 
handshapes.

And it is not trivial, because “same” start/end handshapes refers to
abstract linguistic properties, not the surface phonetic properties that
are represented by handshape choices.  So, you could correctly choose
“same start/end handhapes” and yet have different actual handshapes
chosen (e.g., slight phonetic variants).

Of course, “different start/end handshapes” should really be different.
But that is not currently enforced by the program, to my knowledge.
One possibility would be to put in a warning if the user attempts to
save a setting of “different start/end handshapes” but has the
same start and end handshapes selected.  

Thoughts?

thanks,
 Carol

**Comment by blazetravis** [comment]
> One possibility would be to put in a warning if the user attempts to
> save a setting of “different start/end handshapes” but has the
> same start and end handshapes selected.

This would be a useful feature.

**Comment by gregorydimitriadis** [comment]
On the topic of the data of glosses themselves, it is correct that there truly are implemented start and end handshapes, and there are ways to get directly to them (in the case of a hypothetical search on the data structure), but they are not being used in this context in this Morphological-Phonological Info window. The images of the handshapes associated with the gloss entity are the ones which get displayed in Morph-Phon window and on the gloss screen. 

What is not implemented is which handshapes to display, and when/where/under what circumstances. So I suppose that's what I'm hoping to understand. I believe in the past the behavior of start/end with a single handshape was being accomplished by simply copy/pasting the handshape into the second slot.

> So, you could correctly choose
> “same start/end handhapes” and yet have different actual handshapes
> chosen (e.g., slight phonetic variants).

This seems troublesome, because I wonder how to then enforce the 'start/end' behavior. I agree with the idea of a warning on trying to save with 'diff start/end handshapes' and different handshapes selected, but only if "different" is defined in some way.

**Comment by blazetravis** [comment]
Unfortunately this is still not entirely complete.

If I create a new gloss that is more than one frame long with same start/end handshapes but only input one handshape, the actual display of the gloss is acting like a one-frame gloss.

![screen shot 2015-12-01 at 2 18 15 pm](https://cloud.githubusercontent.com/assets/13489587/11511312/637ad474-9836-11e5-864d-2ed990b3007d.png)

**Comment by gregorydimitriadis** [comment]
That particular display issue we can treat as falling under #53

**Comment by blazetravis** [comment]
Then this is complete for now.

**Comment by gregorydimitriadis** [comment]
Thanks Blaze - closing this out.
